<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authentication\**" />
    <Compile Remove="Email\**" />
    <Compile Remove="FileSystem\**" />
    <Compile Remove="Identity\**" />
    <Compile Remove="Interfaces\**" />
    <EmbeddedResource Remove="Authentication\**" />
    <EmbeddedResource Remove="Email\**" />
    <EmbeddedResource Remove="FileSystem\**" />
    <EmbeddedResource Remove="Identity\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <None Remove="Authentication\**" />
    <None Remove="Email\**" />
    <None Remove="FileSystem\**" />
    <None Remove="Identity\**" />
    <None Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\BlazingBudget.Domain\BlazingBudget.Domain.csproj" />
  </ItemGroup>

</Project>
